  version: "3.9"

  services:
    database:
      image: postgres:latest
      restart: always
      environment:
        POSTGRES_PASSWORD: verySecretPassword
        POSTGRES_USER: administrator
        POSTGRES_DB: spamOverflow_database
      volumes:
        - ./data/db:/var/lib/postgresql/data
    app:
      build: .
      restart: always
      environment:
        SQLALCHEMY_DATABASE_URI: 
          postgresql://administrator:verySecretPassword@database:5432/spamOverflow_database
      ports:
        - "8080:8080"
      depends_on:
        - database